Fix NoSuchMethodError: org.wso2.carbon.identity.core.util.IdentityDatabaseUtil.commitTransaction
wso2-extensions/identity-migration-resources pull request #140
Opened 2020-10-06 11:59 UTC by dushaniw

## Purpose
fix https://github.com/wso2/product-apim/issues/9049

## Goals
Add commitTransaction and rollbackTransaction JDBC util methods.

## Tested
JDK 1.8 
Ubuntu 19.04
Oracle 12c with API-M 2.0 to 2.6
Postgres 9.6 with API-M 2.0 to 2.6

2020-10-07 08:19 UTC, inthirakumaaran approved these changes

2020-10-07 08:22 UTC, omindu requested changes

2020-10-07 08:22 UTC, omindu commented on components/org.wso2.is.migration/migration-service/src/main/java/org/wso2/carbon/is/migration/service/v530/util/JDBCPersistenceUtil.java
> +public class JDBCPersistenceUtil {
Add a class level comment

2020-10-07 08:22 UTC, omindu commented on components/org.wso2.is.migration/migration-service/src/main/java/org/wso2/carbon/is/migration/service/v530/util/JDBCPersistenceUtil.java
> +        }
```suggestion
        } catch (SQLException e) {
            log.error("An error occurred while rolling back transactions.", e);
        }
```

2020-10-07 08:22 UTC, omindu commented on components/org.wso2.is.migration/migration-service/src/main/java/org/wso2/carbon/is/migration/service/v530/util/JDBCPersistenceUtil.java
> +        }
```suggestion
        } catch (SQLException e) {
            log.error("An error occurred while commit transactions.", e);
        }
```

2020-10-07 09:59 UTC, inthirakumaaran commented
For IS testing
- Migration from IS 5.2 to IS 5.7 
- With 1000 users, 1000 SPs, authentication code flow for 5 mins using [JMeter scripts](https://github.com/wso2/performance-is/tree/single-node-performance/distribution/scripts/jmeter)
- JDK 1.8
- DB: Postgres 9.5.23, MySql 5.7

2020-10-08 02:17 UTC, dushaniw commented on components/org.wso2.is.migration/migration-service/src/main/java/org/wso2/carbon/is/migration/service/v530/util/JDBCPersistenceUtil.java
> +public class JDBCPersistenceUtil {
fixed

2020-10-08 10:56 UTC, omindu approved these changes

2020-10-08 10:57 UTC, merged